name: itfsd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  device_info_plus: ^9.0.2
  quickalert: ^1.0.1
  permission_handler: ^10.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^9.0.2
  http: ^1.0.0
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  path_provider: ^2.0.15
  build_runner: ^2.4.6
  timezone: ^0.9.2
  image_picker: ^1.0.0
  dio: ^5.3.0
  calendar_date_picker2: ^0.5.2
  dropdown_button2: ^2.3.7
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_datagrid: ^23.1.44
  syncfusion_flutter_calendar: ^23.1.44
  flutter_dotenv: ^5.1.0
  infinite_scroll_pagination: ^4.0.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  flutter_screenutil: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.5
  intl_translation: ^0.18.2
  ionicons: ^0.2.2
  provider: ^6.1.1
  json_annotation: ^4.8.1



dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
#  generate: true

  assets:
      - assets/
      - assets/images/
      - assets/icons/
      - assets/logo/
      - lib/app/resources/ai/
      - lib/app/resources/ai/chatgpt.json
      - lib/app/resources/ai/avatars/
  fonts:
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf


